name: flutter_csv_localization
description: Flutter localizations generator from CSV files.
version: 0.1.0
homepage: https://github.com/aloisdeniel/flutter_csv_localization
author: Aloïs Deniel <alois.deniel@outlook.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  meta:
  csv:
  args:
  recase:
  code_builder:
  dart_style: