name: flutter_csv_localization
description: Flutter localizations generator from CSV files.
version: 0.2.2
homepage: https://github.com/aloisdeniel/flutter_csv_localization
author: Aloïs Deniel <alois.deniel@outlook.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  http: ^0.12.0
  meta: ^1.1.7
  csv: ^4.0.3
  args: ^1.5.1
  recase: ^2.0.1
  code_builder: ^3.2.0
  dart_style: ^1.2.7